// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmhbtglrnlkuclrleuhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtaGJ0Z2xybmxrdWNscmxldWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODMyODksImV4cCI6MjA2NDc1OTI4OX0.F-7vle_TSAHiG91t3H0XOQrjwmrJ2lhyhO0lnR6CEjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);